### ISSUE TITLE
Policies in root deleted when running incomplete playbook on separate vdom

### ISSUE THREAD

**Issue by senilio** [eoprede/ansible_fortios_api#2]
Hi!

Today I ran a playbook containing a mistake against one of our vdoms. The playbook failed, but I noticed that the existing policies in the rood vdom was wiped after running.

Here's a bogus playbook to reproduce the issue:

```
---
    - name: Create rules
      fortios_api_firewall_policy:
        conn_params: "{{ test_fw }}"
        vdom: test_vdom
        policies:
        - policyid: 100
          service: [ { name: HTTPS } ]
          srcintf: [ { name: SUPPORT } ]
          srcaddr: [ { name: AD } ]
          dstintf: [ { name: APP } ]
          dstaddr: [ { name: all } ]
          action: accept
          schedule: always
          name: HTTPS traffic
        - policyid: 200
          service: [ { name: HTTP } ]
          srcintf: [ { name: SUPPORT } ]
          srcaddr: [ { name: AD } ]
          dstintf: [ { name: APP } ]
          dstaddr: [ { name: all } ]
          action: accept
          schedule: always
          name: PA traffic
        - policyid: 300
          service: [ { name: FTP } ]
          srcintf: [ { name: SUPPORT } ]
          srcaddr: [ { name: AD } ]
          dstintf: [ { name: APP } ]
          dstaddr: [ { name: all } ]
          action:
          schedule: always
          name: FTP traffic
```

The error is with rule id 300, as it's missing an action. The playbook fails with:
```
fatal: [localhost]: FAILED! => {"changed": false, "end_state": [], "existing": [], "msg": "Update failed, successfully rolled back to original configuration.", "proposed": .........
```

But when taking a look in the root vdom, it's empty :)

I have no idea if this is an error with the FortiOS API or with your Ansible module, but I've managed to reproduce on 2 different firewalls, running versions v5.4.8,build1183 (GA) and v5.6.4 build1575 (GA). It might be worth investigating further to rule out one or the other 👍  Thanks!

**Comment by eoprede** [comment]
Just to clarify: 
1) Is the whole vdom config gone or just the policy part of it?
2) Are you using Ansible 2.5? If yes, could you please test with 2.4? This code has never been tested on 2.5 and I don't know of any potential gotchas with it.

**Comment by senilio** [comment]
Hi,

1. Only the policy part is gone.
2. It's been tested on both Ansible 2.5.0 and 2.4.2 with the same result.

**Comment by eoprede** [comment]
Just tested this with
```
test@nipap:~/ansible_tests/test$ ansible --version
ansible 2.6.0 (devel fe4368ce15) last updated 2018/05/18 10:37:30 (GMT -400)
  config file = None
  configured module search path = [u'/home/test/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/test/ansible_tests/ansible/lib/ansible
  executable location = /home/test/ansible_tests/ansible/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

and it worked as expected, failing the run, but not affecting any current config. Tested on Fortigate 80c with 5.6.4 code.

Playbook for reference (note that 1st 2 rules were already configured):
```
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    test_fw:
      fortigate_username: admin
      fortigate_password: p@$$w0rd
      fortigate_ip: "192.168.0.4"
      secure: true
      verify: false
  tasks:
  - name: Create rules
    fortios_api_firewall_policy:
      conn_params: "{{ test_fw }}"
      vdom: test_vdom
      policies:
      - policyid: 100
        service: [ { name: HTTPS } ]
        srcintf: [ { name: SUPPORT } ]
        srcaddr: [ { name: AD } ]
        dstintf: [ { name: APP } ]
        dstaddr: [ { name: all } ]
        action: accept
        schedule: always
      - policyid: 200
        service: [ { name: HTTP } ]
        srcintf: [ { name: SUPPORT } ]
        srcaddr: [ { name: AD } ]
        dstintf: [ { name: APP } ]
        dstaddr: [ { name: all } ]
        action: accept
        schedule: always
      - policyid: 300
        service: [ { name: FTP } ]
        srcintf: [ { name: SUPPORT } ]
        srcaddr: [ { name: AD } ]
        dstintf: [ { name: APP } ]
        dstaddr: [ { name: all } ]
        action:
        schedule: always
        name: FTP traffic
```

**Comment by eoprede** [comment]
It looks like one of our differences is that I run ansible from source, while you are installing it. I have replicated the setup in docker container and again was not able to replicate the issue (same goes for the other issue that you saw). 
Do you mind trying your playbook from container? That would ensure that we have at least identical environments that we run module from.
Here's the instructions you can follow: http://ruleoftech.com/2017/dockerizing-all-the-things-running-ansible-inside-docker-container
But instead of using the dockerfile they are referencing, please use the following one: https://justpaste.it/2k6jq 
This will set up Ansible environment with additional fortios_api modules and then you can try your playbooks from it.

**Comment by senilio** [comment]
Hi!

I have setup the Ansible env using the provided instructions and your Dockerfile. I managed to replicate the issue once again, but I noticed a requirement for being able to replicate the issue. This also goes for my previous tests, so there's nothing different when running from the Docker environment.

The policy section in test_vdom must be empty before applying the playbook. The issue does not happen when there are rules previously configured test_vdom. So please try the following:

1. Remove all policies from test_vdom before applying the playbook with all 3 rules (with the 3rd containing the error): https://github.com/eoprede/ansible_fortios_api/issues/2#issuecomment-390292745
2. Also make sure that the root vdom contains at least one policy before applying so we notice something being wiped.

I noticed this thanks to your comment "Playbook for reference (note that 1st 2 rules were already configured)". When having the first 2 rules pre configured, I couldn't replicate the issue either. Hopefully this will help you. Thanks!

**Comment by eoprede** [comment]
Thanks, I was able to replicate the issue. The error appears when empty config is being applied to the vdom - it not only deletes config in given vdom, but root vdom as well. So this playbook triggers it as well:
```
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    test_fw:
      fortigate_username: admin
      fortigate_password: p@$$w0rd
      fortigate_ip: "192.168.0.4"
      secure: true
      verify: false
  tasks:
  - name: Create rules
    fortios_api_firewall_policy:
      conn_params: "{{ test_fw }}"
      vdom: test_vdom
      policies:
```
I'll take a look at what's causing it.
