### ISSUE TITLE
IndexError: list index out of range, when adding new policies.

### ISSUE THREAD

**Issue by senilio** [eoprede/ansible_fortios_api#3]
Hi again,

I've noticed an issue I can't really explain. I get this whenever I try to add rules to a VDOM:

```fatal: [localhost]: FAILED! => {"changed": false, "module_stderr": "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:769: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html\n  InsecureRequestWarning)\nTraceback (most recent call last):\n  File \"/tmp/ansible_OcTpsO/ansible_module_fortios_api_firewall_policy.py\", line 340, in <module>\n    main()\n  File \"/tmp/ansible_OcTpsO/ansible_module_fortios_api_firewall_policy.py\", line 336, in main\n    forti_api.apply_configuration_to_endpoint()\n  File \"/tmp/ansible_OcTpsO/ansible_module_fortios_api_firewall_policy.py\", line 228, in apply_configuration_to_endpoint\n    self._move_existing_policies()\n  File \"/tmp/ansible_OcTpsO/ansible_module_fortios_api_firewall_policy.py\", line 271, in _move_existing_policies\n    self._move_policy(mpol_target_index)\n  File \"/tmp/ansible_OcTpsO/ansible_module_fortios_api_firewall_policy.py\", line 281, in _move_policy\n    mpol_target_index]['policyid']\nIndexError: list index out of range\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}```

So for instance, if I first have this playbook applied and accepted by the Fortgate:

```
---
    - name: Create rules
      fortios_api_firewall_policy:
        conn_params: "{{ test_fw }}"
        vdom: test_vdom
        policies:
        - policyid: 100
          service: [ { name: HTTPS } ]
          srcintf: [ { name: SUPPORT } ]
          srcaddr: [ { name: AD } ]
          dstintf: [ { name: APP } ]
          dstaddr: [ { name: all } ]
          action: accept
          schedule: always
```

And then add another rule, so our playbook looks like this, then run the new playbook:

```
---
    - name: Create rules
      fortios_api_firewall_policy:
        conn_params: "{{ test_fw }}"
        vdom: test_vdom
        policies:
        - policyid: 100
          service: [ { name: HTTPS } ]
          srcintf: [ { name: SUPPORT } ]
          srcaddr: [ { name: AD } ]
          dstintf: [ { name: APP } ]
          dstaddr: [ { name: all } ]
          action: accept
          schedule: always
        - policyid: 200
          service: [ { name: HTTP } ]
          srcintf: [ { name: SUPPORT } ]
          srcaddr: [ { name: AD } ]
          dstintf: [ { name: APP } ]
          dstaddr: [ { name: all } ]
          action: accept
          schedule: always
```

I expect the second rule to be added to the existing set of rules, but instead we get the error stated at the top.  To get past this, we can manually delete the existing rules in out VDOM, then run the script again.

Versions:
```
$ ansible --version
ansible 2.5.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/emipet/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.5 (default, Nov  6 2016, 00:28:07) [GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

Thanks

**Comment by senilio** [comment]
The new rule seems to be added correctly, even though I get the error. When running the same playbook a second time, it's accepted.

**Comment by eoprede** [comment]
Just tested this with
```
test@nipap:~/ansible_tests/test$ ansible --version
ansible 2.6.0 (devel fe4368ce15) last updated 2018/05/18 10:37:30 (GMT -400)
  config file = None
  configured module search path = [u'/home/test/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/test/ansible_tests/ansible/lib/ansible
  executable location = /home/test/ansible_tests/ansible/bin/ansible
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

and it worked as expected without any issues. Tested on Fortigate 80c with 5.6.4 code.
Playbook for reference (1st execution had only the 1st rule, 2nd had both rules).

```
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    test_fw:
      fortigate_username: admin
      fortigate_password: p@$$w0rd
      fortigate_ip: "192.168.0.4"
      secure: true
      verify: false
  tasks:
  - name: Create rules
    fortios_api_firewall_policy:
      conn_params: "{{ test_fw }}"
      vdom: test_vdom
      policies:
      - policyid: 100
        service: [ { name: HTTPS } ]
        srcintf: [ { name: SUPPORT } ]
        srcaddr: [ { name: AD } ]
        dstintf: [ { name: APP } ]
        dstaddr: [ { name: all } ]
        action: accept
        schedule: always
      - policyid: 200
        service: [ { name: HTTP } ]
        srcintf: [ { name: SUPPORT } ]
        srcaddr: [ { name: AD } ]
        dstintf: [ { name: APP } ]
        dstaddr: [ { name: all } ]
        action: accept
        schedule: always
```

**Comment by senilio** [comment]
I've made some more testing regarding this issue, and I believe I have found a sure way to reproduce.

1. Apply the following playbook:

```
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    test_fw:
      fortigate_username: admin
      fortigate_password: p@$$w0rd
      fortigate_ip: "192.168.0.4"
      secure: true
      verify: false
  tasks:
  - name: Create rules
    fortios_api_firewall_policy:
      conn_params: "{{ test_fw }}"
      vdom: test_vdom
      policies:
      - policyid: 100
        service: [ { name: HTTP } ]
        srcintf: [ { name: SUPPORT } ]
        srcaddr: [ { name: AD } ]
        dstintf: [ { name: APP } ]
        dstaddr: [ { name: all } ]
        action: accept
        schedule: always
```

After it's applied correctly, run the following playbook:

```
---
- hosts: localhost
  connection: local
  gather_facts: false
  vars:
    test_fw:
      fortigate_username: admin
      fortigate_password: p@$$w0rd
      fortigate_ip: "192.168.0.4"
      secure: true
      verify: false
  tasks:
  - name: Create rules
    fortios_api_firewall_policy:
      conn_params: "{{ test_fw }}"
      vdom: test_vdom
      policies:
      - policyid: 95
        service: [ { name: HTTP } ]
        srcintf: [ { name: SUPPORT } ]
        srcaddr: [ { name: AD } ]
        dstintf: [ { name: APP } ]
        dstaddr: [ { name: all } ]
        action: accept
        schedule: always
      - policyid: 100
        service: [ { name: HTTP } ]
        srcintf: [ { name: SUPPORT } ]
        srcaddr: [ { name: AD } ]
        dstintf: [ { name: APP } ]
        dstaddr: [ { name: all } ]
        action: accept
        schedule: always
```

This consistently produces the following error in my testing:
```File \"/tmp/ansible_gMXLHQ/ansible_module_fortios_api_firewall_policy.py\", line 281, in _move_policy\n    mpol_target_index]['policyid']\nIndexError: list index out of range```

It seems to have something to do with the fact that the new policy is defined before the existing one in the playbook. I hope this helps to reproduce.

As stated earlier, if I rerun the second playbook, it's accepted without issues.
